- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
  tasks:
    - include: ansible/zsh.yml
    - include: ansible/node.yml
    - include: ansible/vim.yml
