- name: Install git
  apt: name=git
  tags:
    - git
- name: Copy .global.gitignore
  copy:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/git/.global.gitignore"
    dest: "{{ lookup('env', 'HOME') }}/.global.gitignore"
  tags:
    - dotfiles
    - git
- name: Config Git .global.gitignore
  shell: git config --global core.excludesfile "$HOME/.global.gitignore"
  tags:
    - git
- name: Config Git
  shell: git config --global user.name "Cuong Tran"
  tags:
    - git

