- name: Install git
  apt: name=git
  tags:
    - git
- name: Copy .global.gitignore
  shell: mv ~/dotfiles/git/.global.gitignore ~/.global.gitignore
  tags:
    - dotfiles
    - git
- name: Config Git global.ignore
  shell: git config --global core.excludesfile '~/.global.gitignore'
  tags:
    - git
