- name: Install git
  apt: name=git
  tags:
    - git
- name: Copy .global.gitignore
  copy:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/git/.global.gitignore"
    dest: "{{ lookup('env', 'HOME') }}/.global.gitignore"
  tags:
    - dotfiles
    - git
- name: Config Git global.ignore
  shell: git config --global core.excludesfile '/home/docker/.global.gitignore'
  tags:
    - git
