- name: Install node
  become: true
  apt:
    name: [nodejs, npm]
    state: present
  tags:
    - node
- name: Install n
  become: true
  npm:
    name: n
    global: true
  tags:
    - node
- name: n 18
  become: true
  shell: n 18
  tags:
    - node
- name: typescript
  become: true
  shell: npm install -g typescript
  tags:
    - node
