- name: Install Tmux
  apt: name=tmux
  tags:
    - tmux
- name: Copy .tmux.config
  copy:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/tmux/.tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"
  tags:
    - dotfiles
    - tmux

