- name: Copy .vimrc
  copy:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/vim/.vimrc"
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"
  tags:
    - dotfiles
    - vim
- name: Install Vim dependencies
  become: true
  apt:
    name: [git ,libatk1.0-dev ,libcairo2-dev ,libgtk2.0-dev ,liblua5.1-0-dev ,libncurses5-dev ,libperl-dev ,libx11-dev ,libxpm-dev ,libxt-dev ,lua5.1 ,python3-dev ,ruby-dev ,clang ,make, cmake]
  tags:
    - vim
- name: Clone vim
  become: true
  ansible.builtin.git:
    repo: https://github.com/vim/vim.git
    dest: "{{ lookup('env', 'HOME') }}/vim"
  tags:
    - vi
- name: Install Vim
  become: true
  shell: {{ lookup('env', 'HOME') }}/dotfiles/vim/setup.sh
  tags:
    - vim
